# Generated by Django 5.2.11 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, default='', help_text='Identify your team (e.g., Team Alpha)', max_length=100),
        ),
    ]
