# Generated by Django 5.2.11 on 2026-03-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('response_time', models.FloatField(default=0.0, help_text='Response time in seconds')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNASequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(help_text='The cleaned DNA sequence (ATGC only)')),
                ('prediction', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Prediction confidence (0-1)')),
                ('ai_explanation', models.TextField(blank=True, default='')),
                ('ai_suggestions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnasequence_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNA Sequence',
                'verbose_name_plural': 'DNA Sequences',
                'ordering': ['-created_at'],
            },
        ),
    ]
